<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\GraphBuilder.Application\GraphBuilder.Application.csproj" />
		<ProjectReference Include="..\GraphBuilder.Domain\GraphBuilder.Domain.csproj" />
		<PackageReference Include="Avalonia" Version="11.3.9" />
		<PackageReference Include="MathParser.org-mXparser" Version="6.1.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
		<PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
	</ItemGroup>
</Project>